title: Your awesome title
author: Sahil Bansal
email: bansalsahil740@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
 hiii
 thanks for visiting.
# social links
twitter_username: sahilbansalll
github_username:  sahilbnsll

show_excerpts: true # set to false to remove excerpts on the homepage
